### ISSUE TITLE
Feature request: document full options in README.md

### ISSUE THREAD

**Issue by breedx2** [NatalieWolfe/node-promise-pool#1]
First, thanks for this great library!  

For my utterly simple usage, I have some fixed, inexpensive resources that I'd like to treat as a generic pool.  After reading the README and hacking up a simple example with min = max = 50, I was surprised to see the pool continue to create the resources.  Fortunately, the code is well documented and easy to read, so I was able to find and use the `refreshIdle: false` setting, which is exactly what I needed!

It would be nice to have the complete set of options documented in the README to prevent others from having to dig inside the source.  I think it could also help this lib's adoption, because you've got quite a bit of features in there that people might not realize.

Thanks again!

**Comment by NatalieWolfe** [comment]
Thanks for using it, I'm glad you like it! I do have all the options documented in the code as you saw, and I have generated JS docs hosted here http://nataliewolfe.github.io/node-promise-pool/docs/. While I do agree that more information in the readme would be good, maintaining the full list of options in two places could lead to fragmentation in the documentation. That and I'm really lazy. :)

I'll see about making the documentation link more obvious and if there is any way I can get jsdoc to generate the readme for me, maybe as part of the npm prepublish script.

Please let me know if there are any other features or improvements you'd like to see!

**Comment by breedx2** [comment]
I totally understand the need to not have to maintain docs in two places.  I didn't even realize that docs page was over there!

Maybe just a simple blurb in the README like:

"There are a bunch more useful features like idle timeout control and pool usage and onRelease that are documented over here:  http://nataliewolfe.github.io/node-promise-pool/docs/index.html"

That would have helped me!  :smile:   Thanks again.

**Comment by NatalieWolfe** [comment]
I've added the factory options to the readme and made the link to the Github hosted documentation more obvious. Let me know if that satisfies your request!
